services:
  nginx:
    image: nginx:latest
    container_name: vaca-track-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: ./src
    container_name: vaca-track
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: vaca-track-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: vaca_track
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      retries: 10

volumes:
  db_data: